
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/west_yorkshire_latest_railway_crossing.geojson", function(data)
{
    append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/scotland/crossings/scotland_latest_railway_crossing.geojson", function(data)
{
    append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/greater_london_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/suffolk_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/essex_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/east_sussex_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/tyne_and_wear_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/derbyshire_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/durham_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/east_yorkshire_with_hull_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/cambridgeshire_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/wiltshire_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/hertfordshire_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/kent_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/northamptonshire_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/hampshire_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/cornwall_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/northumberland_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/rutland_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/cumbria_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/merseyside_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/somerset_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/bedfordshire_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/north_yorkshire_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/nottinghamshire_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/lancashire_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/surrey_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/lincolnshire_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/berkshire_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/oxfordshire_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/bristol_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/herefordshire_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/cheshire_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/shropshire_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/staffordshire_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/worcestershire_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/buckinghamshire_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/isle_of_wight_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/leicestershire_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/dorset_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/warwickshire_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/gloucestershire_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/south_yorkshire_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/west_midlands_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/west_sussex_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/norfolk_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/devon_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/crossings/greater_manchester_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/wales/crossings/wales_latest_railway_crossing.geojson",function(data){
        append_crossing_json_data(data);
}
);