
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/west_yorkshire_latest_railway_rail.geojson", function(data)
{
    append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/scotland/railways/mainline/scotland_latest_railway_rail.geojson", function(data)
{
    append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/greater_london_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/suffolk_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/essex_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/east_sussex_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/tyne_and_wear_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/derbyshire_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/durham_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/east_yorkshire_with_hull_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/cambridgeshire_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/wiltshire_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/hertfordshire_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/kent_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/northamptonshire_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/hampshire_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/cornwall_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/northumberland_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/rutland_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/cumbria_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/merseyside_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/somerset_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/bedfordshire_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/north_yorkshire_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/nottinghamshire_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/lancashire_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/surrey_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/lincolnshire_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/berkshire_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/oxfordshire_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/bristol_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/herefordshire_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/cheshire_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/shropshire_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/staffordshire_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/worcestershire_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/buckinghamshire_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/isle_of_wight_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/leicestershire_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/dorset_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/warwickshire_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/gloucestershire_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/south_yorkshire_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/west_midlands_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/west_sussex_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/norfolk_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/devon_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/england/railways/mainline/greater_manchester_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
$.getJSON("https://raw.githubusercontent.com/artemis-beta/OpenRailChart/railgeodata/wales/railways/mainline/wales_latest_railway_rail.geojson",function(data){
        append_railway_json_data(data);
}
);
